// This file is generated by Slice Machine. Update with care!

import CodeSnippet from './CodeSnippet';
import Image from './Image';
import Paragraph from './Paragraph';

export {
	CodeSnippet,
	Image,
	Paragraph,
};

export const components = {
	code_snippet: CodeSnippet,
	image: Image,
	paragraph: Paragraph,
};
