// This file is generated by Slice Machine. Update with care!

import Embed from './Embed';
import Post from './Post';

export {
	Embed,
	Post,
};

export const components = {
	embed: Embed,
	post: Post,
};
