# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  pull_request:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job check for code linting errors
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Setup Environment it will run
    environment:
      name: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Beginning Linting
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
        with:
          # Access all commit history
          fetch-depth: 0

        # Setup node
      - name: Use Node 16
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x

        # Get cached node_modules to fast workflow
      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

        # Install Dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

        # Run ESLint
      - name: Run ESLint
        run: yarn lint

  # This job run unit and E2E tests
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Setup Environment it will run
    environment:
      name: dev

    # Only run if tests run ok
    needs: lint

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Beginning Testing
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
        with:
          # Access all commit history
          fetch-depth: 0

        # Setup node
      - name: Setup Node 16
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x

        # Get cached node_modules to fast workflow
      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

        # Install Dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

        # Run ESLint
      - name: Run Tests
        run: yarn test:ci
      
      - name: Generate coverage report
        run: |
          yarn jest --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
